- group: Kubernetes
  priority: 1
  metrics:
  - title: "Memory usage"
    y_label: "Values"
    required_metrics:
      - container_memory_usage_bytes
    weight: 1
    queries:
    - query_range: 'avg(container_memory_usage_bytes{%{environment_filter}}) / 2^20'
      label: Container memory
      unit: MiB
  - title: "Current memory usage"
    required_metrics:
     - container_memory_usage_bytes
    weight: 1
    queries:
    - query: 'avg(container_memory_usage_bytes{%{environment_filter}}) / 2^20'
      display_empty: false
      unit: MiB
  - title: "CPU usage"
    required_metrics:
     - container_cpu_usage_seconds_total
    weight: 1
    queries:
    - query_range: 'avg(rate(container_cpu_usage_seconds_total{%{environment_filter}}[2m])) * 100'
  - title: "Current CPU usage"
    required_metrics:
     - container_cpu_usage_seconds_total
    weight: 1
    queries:
    - query: 'avg(rate(container_cpu_usage_seconds_total{%{environment_filter}}[2m])) * 100'
